---
- name: nginx_availability
  become: true
  hosts: all
  vars:
    key_file: /etc/nginx/ssl/nginx.key
    cert_file: /etc/nginx/ssl/nginx.crt
  tasks:
    - name: "check if nginx is installed"
      apt:
        name: nginx
        state: present

    - name: create ssl directory
      file:
        path: /etc/nginx/ssl
        state: directory

    - name: copy key_file
      copy:
        src: files/nginx.key
        dest: "{{ key_file }}"
        mode: 0400
        owner: root
        group: root

    - name: copy cert_file    
      copy: 
        src: files/nginx.crt
        dest: "{{ cert_file }}"
        mode: 0644
        owner: root
        group: root

    - name: update default.conf on remote server
      template: 
        src: template/default.conf.j2
        dest: /etc/nginx/conf.d/default.conf
        mode: 0644
        owner: root
        group: root
        backup: yes
    
      notify: restart nginx
    
  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted     
